version: "2.4"

services:

  api:
    depends_on:
      mongo:
        condition: service_healthy
    extends:
      file: api/docker-compose.yml
      service: api
    env_file: api/.env

  mongo:
    image: mongo
    ports:
      - 27017:27017
    healthcheck:
      test: "exit 0"
